[package]
name = "trait_tests"
description="A compiler plugin to allow tests to be defined agaist traits."
version = "0.1.0"
authors = ["Giles Cope <gilescope@gmail.com>"]
repository = "https://github.com/gilescope/trait_tests"
readme="README.md"
keywords=["testing", "test", "traits"]
categories=["development-tools::testing"]
maintenance= { status="experimental" }
license="MIT"

[lib]
proc-macro = false
crate-type = ["dylib"]


[dependencies]
